### ISSUE TITLE
[Feature request] Make Changelogger compatible with Thunderbird

### ISSUE THREAD

**Issue by bege10** [Rayquaza01/changelogger#14]
Hello,
I very much appreciate Changelogger for Firefox. I managed to install it also to Thunderbird, but unfortunately it does not work there. Can you, please, make Changelogger compatible with Thunderbird?

**Comment by Rayquaza01** [comment]
Hello,
Changelogger is now compatible with Thunderbird. It is available here: https://addons.thunderbird.net/addon/changelogger/

While it has the same version number (v1.1.1) as the Firefox version, there are some minor changes between it and the Firefox version. You can see all of the changes on the [thunderbird](https://github.com/Rayquaza01/changelogger/tree/thunderbird) branch of this repo.

 * Thunderbird addons are served from addons.thunderbird.net. References to addons.mozilla.org in the code are replaced with addons.thunderbird.net
 * `browser.storage.sync` does not seem to work correctly in Thunderbird. References to `browser.storage.sync` in the code are replaced with `browser.storage.local`

It might be possible to create one version that works on both Firefox and Thunderbird without manually making changes to the code by checking where it's running using `browser.runtime.getBrowserInfo()`, but this seems to throw an error on Thunderbird.


Let me know if you have any issues using the Thunderbird version!

**Comment by bege10** [comment]
@Rayquaza01 
Perfect! Changelogger just noticed me of Changelogger being updated 😁
It looks like it works correct now. Settings can be managed also now.
Thank you so much 🙏
