### ISSUE TITLE
dark popup icon

### ISSUE THREAD

**Issue by kinghat** [Rayquaza01/changelogger#2]
would you take a pull request to have a dark mode icon made for people who have dark themes set for the browser? the black is hard to see. i would probably make it the same color as standard gray from the default dark theme:

![image](https://user-images.githubusercontent.com/16073360/67166337-e0bf9d80-f353-11e9-8272-6a108156257b.png)

if you give the go ahead would you want it tied into the current theme selection option or have it as a standalone option?

**Comment by Rayquaza01** [comment]
I actually just fixed it with 55cf1af56433ff536d2df94b4ad10b6a78e4edd6. It was actually supposed to do that already, but I accidentally left a `fill="#000000"` in the SVG files, so it wasn't working.
